---
title: "Macro for Many Columns"
author: "Emily Riederer"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["default", "eee.css", "eee-fonts.css", "table.css"]
    nature:
      beforeInit: "table_macro.js"
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```


## Splitting slides into two columns is already pretty easy

.pull-left[.full-width[ 

You can just write:

`.pull-left[.full-width[<insert content>]]` 

for content to go on the left-hand side

]]



.pull-right[.full-width[ 

...and similarly write:

`.pull-right[.full-width[<insert content>]]` 

for contents to go on the right-hand side

]]


---

class: inverse, center, middle

## But what if you want more than two columns?

---

class: inverse, center, middle

## It's macro time!

---

## Basic idea is to create column structure row-by-row

`![:col_header x, y, z]`: creates header with CSS class `multicolhead` for styling

`![:col_list x, y, z]`: creates row of bulletted list items for each column

`![:col_row x, y, z]`: creates row of text for each column

---

## For example, writing this...

````html
![:col_header Header 1, Header 2, Header 3]
![:col_list You can add rows with bulletted lists, item2, item3]
![:col_list item4, item5, Or normal chunks of text (see below)]
![:col_row 
    This is a long descriptive paragraph about a point 
    that I need to explain in great details for it to 
    be fully understood,
    
    This is another long explanatory piece. Sometimes you need 
    to provide you readers a lot of information,
    
    Testing testing 1 2 3. Let's make this a little longer]
````
---

## Three column layouts are easy

![:col_header Header 1, Header 2, Header 3]
![:col_list You can add rows with bulletted lists, item2, item3]
![:col_list item4, item5, Or normal chunks of text (see below)]
![:col_row 
    This is a long descriptive paragraph about a point that I need to explain in great details
    for it to be fully understood,
    
    This is another long explanatory piece. Sometimes you need to provide you readers a lot 
    of information,
    
    Testing testing 1 2 3. Let's make this a little longer]

---

## Or four!

![:col_header Header 1, Header 2, Header 3, Header 4]
![:col_list You can add rows with bulletted lists, item2, item3, hello]
![:col_list item4, item5, Or normal chunks of text (see below), la la la]
![:col_row 
    This is a long descriptive paragraph about a point that I need to explain in great details
    for it to be fully understood,
    
    This is another long explanatory piece. Sometimes you need to provide you readers a lot 
    of information,
    
    Testing testing 1 2 3,
    
    I'm in the fourth column]
    
---

## Or five!

### But it starts to get crowded...

![:col_header Header 1, Header 2, Header 3, Header 4, Header 5]
![:col_list You can add rows with bulletted lists, item2, item3, hello, more content]
![:col_list item4, item5, Or normal chunks of text (see below), la la la, tra la la]
![:col_row 
    More text,
    More text,
    .,
    More text,
    More text
]

---

## It's not perfect

### Header text spills over

![:col_header Super Long Headers Are Not My Friend, Header 2, Header 3]
![:col_list You can add rows with bulletted lists, item2, item3]
![:col_list item4, item5, Or normal chunks of text (see below)]

---

## It's not perfect

### Long single-word headers can get cut-off

![:col_header Super Long Headers Are Not My Friend, This_is_all_one_very_very_long_word, Header 3]
![:col_list You can add rows with bulletted lists, item2, item3]
![:col_list item4, item5, Or normal chunks of text (see below)]

---


## It's not perfect

### It's hard to have a totally blank cell

````html
![:col_header Header 1, Header 2, Header 3]
![:col_row content1, , content3]
````

doesn't honor the blank:

![:col_header Header 1, Header 2, Header 3]
![:col_row content1, , content3]

---

## It's not perfect

### Commas separate columns so can't be used within

````html
![:col_header Header 1, Header 2, Header 3]
![:col_row I wish this would be in column 1, and this would also be in column 1]
````

doesn't honor the blank:

![:col_header Header 1, Header 2, Header 3]
![:col_row I wish this would be in column 1, and this would also be in column 1]


---

## But for now it gets the job done

I like it better than current alternatives

![:col_header Just Using Rows, Raw HTML in Markdown, Macro]
![:col_row <b>Pro</b>, <b>Pro</b>, <b>Pro</b>]
![:col_list 
  Easy to implement without custom scripting,
  Flexibility for custom styling, 
  Cleaner syntax is docs 
]
![:col_row <b>Con</b>, <b>Con</b>, <b>Con</b>]
![:col_list 
  Makes info seem sequential vs parallel,
  Bulky to leave in code, 
  Limitations described before 
]
![:col_list 
  One option could get boring,
  More typo-prone and less repeatable, 
    
]